### ISSUE TITLE
3v3 Imperial Troopers are not a hard counter for Talzin NS

### ISSUE THREAD

**Issue by bobbybaxter** [bobbybaxter/swgoh-counters#113]
_## Issue created anonymously for a user ##_
For Assaj lead, this 3v3 team (Veers, Stark & Range) work as a hard counter well - but for Talzin lead w/ Zombie & Acolyte this team gets trampled.  With no healing, Plague stacks up quickly and wipes the team within a few turns.

I've tested this extensively, as I use your lists religiously... I wanted to be 100% before I reached out to you.

Everyone in the SWGOH community sincerely appreciates all of your hard work in putting this together.  You are legend.

**Comment by Dngrwtchurslf** [comment]
Thank you for posting this issue – I appreciate you!

**Comment by bobbybaxter** [comment]
Updated.  I really appreciate the help on this one!
