### ISSUE TITLE
How JTR hard counters KrU lead

### ISSUE THREAD

**Issue by bobbybaxter** [bobbybaxter/swgoh-counters#153]
_## Issue created anonymously for a user ##_
The goal here is to use JTRs locked healing immunity to keep KrU suppressed until he’s defeated. Then, focus on their damage dealers (FoTp, FoX) and it’ll be an easy win

However, JTRs TM train will be completely shut down against an enemy FO team with zGeneral Hux, so if the opponent does happen to have General Hux with his zeta, it is not at all advisable to use JTR

**Comment by Ze-Forgotten** [comment]
JTR's team relies on turn meter being constantly fueled by exposes and the hard shutdown that JTR can do on enemies, as well as BB8 calling several allies to assist and the massive boost with his 2nd special. 

KrU's team relies on CONSTANTLY scoring critical hits to keep the turn meter train going for them. If you can break at least one of them, the entire turn meter train gets derailed. But with the addition of a zGeneral Hux, that acts as a buffer as well as screwing up JTR's own turn meter train. 

In my eyes, I believe the 1st people to go after are the ones who can fuel TM, such as FoO and Kr. However, you have to keep KrU and the others on lockdown while this happens, so JTR's needs to be quick to lock down the other characters.

With the addition of Resistance Hero Finn and Poe, you get more ways of shutting down and locking Fo units as well as counters and AoE's. Don't forget that RhP can let your team deal big dmg by making the enemies always take critical dmg.

Of course, if a ZGeneral Hux is there, you need to take him out quick with Assist.

**Comment by bobbybaxter** [comment]
added.  thanks!

**Comment by Ze-Forgotten** [comment]
No problem!
