### ISSUE TITLE
Regarding 3v3 to defeat Pal/Malak/Bastilla

### ISSUE THREAD

**Issue by bobbybaxter** [bobbybaxter/swgoh-counters#185]
_## Issue created anonymously for a user ##_
How would I post the new strategy. It could almost be considered a hard counter!

**Comment by chandal9** [comment]
I faced:
G12 Palatine Lead/R7 Malak/R4 Bastilla

I used: 
R2 Traya Lead/R7 Palatine/G12 Nihilus

Nihilus' cool down increase keeps Darth Malak from doing any serious damage & Palpatines Shock keeps him from healing. The Ally health regeneration and debuff dispels from Trayas leadership along with protection up from isolate are enough for Nihilus to annihilate Malak and then the remainder of the enemy's.

**Comment by bobbybaxter** [comment]
added.  thanks!

**Comment by chandal9** [comment]
Thank you!! Your site is awesome btw! I've shared with my guild and they
think the same. I've also become a pattern to support your goal of landing
a domain. Thanks again and good luck!

Chris
