### ISSUE TITLE
Geonosians Counter - First Order (KRU L)

### ISSUE THREAD

**Issue by hirenshah** [bobbybaxter/swgoh-counters#206]
The strategy text states:
_Sith Trooper required, as he'll gain a bonus turn and extra damage with Vengeant Blast whenever a FO ally is defeated._ 

None of the characters mentioned are _Sith Trooper_... is it meant to say _Sith Trooper_, or something else?

**Comment by bobbybaxter** [comment]
updated for clarity.  thanks!
