### ISSUE TITLE
Wampa Phoenix Counter?

### ISSUE THREAD

**Issue by StrangeFury** [bobbybaxter/swgoh-counters#32]
Is Wampa considered a strong Phoenix counter?

**Comment by bobbybaxter** [comment]
Yep, I would consider it a strong counter.  My list currently has Rex/Wampa as a hard counter since Rex is a common leader to feed turn meter to Rex.  However, I'm going to update the list to include just Wampa because so many people have been confused by this.

**Comment by bobbybaxter** [comment]
I've updated Phoenix to show Wampa (Solo) as a hard counter.
