### ISSUE TITLE
Mon Mothma Lead Counter with Jawas (Mon Mothma is now in top 25 GAC Def Meta)

### ISSUE THREAD

**Issue by bobbybaxter** [bobbybaxter/swgoh-counters#341]
_## Counter submission created anonymously for a user ##_
<p><b>Opponent Team:</b> Mon Mothma (L), Chirrut, Baze, K2SO, Cassian (or other rebel fighters, sub K2SO/Cassian for Wedge/Biggs)<br/><b>Counter Team:</b> Jawas<br/><b>Type:</b> 5v5<br/><br/>I’m seeing Mon Mothma (MM) come up often in higher GA tiers (and now in top 25 GAC meta) and TW. Very solid Defensive team that can steal tickets/time out very good teams if not prepared. Often underestimated. Mon Mothma’s stars don’t matter much (I run her at 5*), but she MUST have BOTH ZETAS). MM zetas prevent her from being targeted and allow her to share/spread the total stats across whole team, with constant heal/revive/counter attacks, but extremely low damage. So it plays perfectly into Jawa’s...the can typically survive the first couple volleys, but stack tremendous amounts of bombs afterwards. My decent geared G8-G9 Jawa’s DECIMATED a MM in TW, stacking 25-35 bombs on each enemy after first round of volleys. Then BOOM! Utini MF’er! I lost one, they lost MM and 3 others, with one left in yellow, and all synergy bonuses, revives gone...done. Very satisfying, the better the Jawas the more effective it is.</p><br/><b>Video Link: </b>

**Comment by Imperial501st** [comment]
Link: https://youtu.be/F_LMWV4tLnE
