### ISSUE TITLE
Bug on website

### ISSUE THREAD

**Issue by bobbybaxter** [bobbybaxter/swgoh-counters#382]
_## Issue created anonymously for a user ##_
<p>When you load the website it starts loading the charts etc of the VS but after scrolling down a bit the whole page goes black permanently, once refreshed it shows briefly again, but once more after scrolling a few seconds to try to locate the team it goes all black again.
It's pretty much not usable anymore </p>

**Comment by bobbybaxter** [comment]
I emailed you directly, but for anyone else that sees this, this issue can be resolved by clearing your cache.

**Comment by martums** [comment]
still occurs in multiple browsers after clearing cache, but close the bug.  🐂💩
