### ISSUE TITLE
SWGOH New Patron: Counters Still Blacked out

### ISSUE THREAD

**Issue by bobbybaxter** [bobbybaxter/swgoh-counters#402]
_## Issue created anonymously for a user ##_
<p>just signed up as a $1 Patron.  My Patreon account & my login for SWC share the same email (stephenandolino@gmail.com).  I unlinked the patreon.  Signed out of both, signed back into both and re-linked the patreon (which says "Active Patreon" now).... and the counters are still blacked out.  Please get back to me, thanks</p>

**Comment by Skyline5gtr** [comment]
Same issue constant black screen

**Comment by bobbybaxter** [comment]
resolved.
