### ISSUE TITLE
Resistance

### ISSUE THREAD

**Issue by bobbybaxter** [bobbybaxter/swgoh-counters#69]
_## Issue created anonymously for a user ##_
Can you add Finn lead resistance? I find them a great counter for Bounty Hunters and be good to see the better counters to beat them

**Comment by BlackV** [comment]
Resistance in general

Jedi Rey (Lead)
BB8
R2
Finn

can finish bossk lead with full health protection

**Comment by bobbybaxter** [comment]
After the addition of Rey (Jedi Training) and the changing of Finn's kit, there isn't enough information available to reliably add a Finn lead Resistance team.  And as BlackV commented, the JTR lead Resistance team can finish a Bounty Hunter (Bossk L) team with full health and protection.

Thanks for the request, though!
